networks:
  parkingnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 192.18.0.0/16

services:
  estacionamiento-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '09112'
      MYSQL_DATABASE: 'estDBFingerPrint'
      MYSQL_USER: 'alextcw'
      MYSQL_PASSWORD: '09112'
    networks:
      parkingnetwork:
        ipv4_address: 192.18.0.10
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql  # Agrega el volumen para la base de datos

  admin-backend:
    image: alextcw/admin-parking:v2.0
    restart: always
    networks:
      parkingnetwork:
        ipv4_address: 192.18.0.20
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - estacionamiento-db
    volumes:
      - images-data:/home/alextcw/Files/images  # Agrega el volumen para las imágenes

volumes:
  db-data:  # Define el volumen para la base de datos
  images-data:  # Define el volumen para las imágenes
